### PR TITLE
Remove about page

### LINKED ISSUE #15: The "about" page is still fake Latin
https://github.com/rakutentech/engineering-blog/blob/main/content/about.md still has placeholder content.

### PR DESCRIPTION
**Pull request by jcayzac**
It's fake latin, and the layout of the page is completely broken anyway.

Closes #15

### CODE REVIEW

**Review by NemoOudeis — APPROVED** [review]
LGTM

the layout (before removing the page) looked fine on my end, just like a post. what do you mean by completely broken?

**Comment by jcayzac** [comment]
> the layout (before removing the page) looked fine on my end, just like a post. what do you mean by completely broken?

This is how `/about/` renders for me, on the `main` branch:

Screen Shot 2021-07-30 at 17 06 08

**Comment by jcayzac** [comment]
It seems to be cause by this:

https://github.com/rakutentech/engineering-blog/blob/3d30736ce6ea92bc44354aad09883d7c09e38a36/assets/scss/main.sass#L153-L156

**Comment by NemoOudeis** [comment]
Screen Shot 2021-07-30 at 17 29 26

Huh for me it renders like this on `main`, I'm on Mac OS, firefox 89.0.2 🤔 

...oh well, we'll look at it once we want an about page^^

**Review by boazy — APPROVED** [review]

**Pull request merged**
