### PR TITLE
update markdown to pdf script

### PR DESCRIPTION
**Pull request by NemoOudeis**
the previous script wasn't running, so I tried to fix it.
I haven't found a fix for the emoji problem yet (running with https://github.com/dalibo/pandocker didn't work for me neither). Any ideas @boazy ?

### CODE REVIEW

**Comment by jcayzac** [comment]
For the emojis you'll need to inject an emoji font I think.

**Comment by jcayzac** [comment]
https://www.google.com/get/noto/help/emoji/

**Comment by NemoOudeis** [comment]
I tried with noto, but I stil struggle to get emojis (or to get text), all I can do is pass fonts to latex (via pandoc, see [manual](https://pandoc.org/MANUAL.html))

```shell
pandoc \
  --pdf-engine=xelatex --mathjax \
  --highlight-style zenburn \
  --variable 'mainfont:Noto Serif' \
  --variable 'sansfont:Noto Sans' \
  --variable 'monofont:Noto Mono' \
  --variable 'mathfont:Noto Emoji' \
  --variable 'CJKmainfont:Noto Sans' 
```

And that still get's me missing emojis. 

The other solutions I found all boil down to "install this latex package" or "use this elaborate tex setup". I don't want to go down that rabbit hole and I want to avoid customizing the docker image. Emojis really don't matter that much for the PDFs, those are just for review.

So unless we have a font (file) contains it all OR there's another way to do this I suggest we forget emojis for the time being.

**Comment by jcayzac** [comment]
What image are we using? The one mentioned in https://github.com/dalibo/pandocker/issues/73 (`add_emojis` tag) ?

**Comment by NemoOudeis** [comment]
I tired the pandocker image with the `add_emojis` tag and that didn't work - so I moved to using `pandoc/latex` instead (both images work interchangably, emojis work on neither - for me).

picking a fixed tag is a good idea tho.

I'm not sure which `pandocker` image boaz used initially 🤷‍♀️

**Comment by boazy** [comment]
I published my pandocker image at ghcr.io. Will be fixing everything shortly :)

**Comment by boazy** [comment]
I replaced this PR with #20

**Pull request closed without merging**
