### PR TITLE
add `hugo mod clean` to deploy script & document the issue

### PR DESCRIPTION
**Pull request by NemoOudeis**

### CODE REVIEW

**Comment by jcayzac** [comment]
@NemoOudeis I think this is not needed anymore with #16 .

**Comment by NemoOudeis** [comment]
I still got the same issue when I was running the #16 code (specifically on commit 6931fae ) :/

**Review by boazy — APPROVED** [review]

**Comment by boazy** [comment]
Looks good but probably not needed. Let's close it for now and reopen again if necessary.

**Comment by boazy** [comment]
Should be fixed by #16

**Comment by boazy** [comment]
Looks good but probably not needed. Let's close it for now and reopen again if necessary.

**Comment by NemoOudeis** [comment]
even with the theme as submodule we are seeing this problem pop up :/
at least @bater and I encounter it from time to time

**Review by jcayzac — APPROVED** [review]

**Pull request merged**
